version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: mongo
          environment: 
            MONGO_DB: contests
    
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: dockerize --wait tcp://localhost:27017 --timout 2m
      - run: node database/loadTestMongoData.js
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build


