version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build


